[package]
name = "libcamera-meta"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
git2 = "0.20"
indoc = "2"
prettyplease = "0.2.29"
semver = "1.0.25"
syn = "2.0"
yaml-rust = "0.4"
